### ISSUE TITLE
v0.2.2.0 server issues

### ISSUE THREAD

**Issue by cdarken** [todxx/tdxminer#4] opened 2018-04-20 10:58 UTC
I think there are some issues with the new version. While with the previous one I was able to mine without issues for 24hrs, this one failed after about 3hrs, it stopped submitting shares to f2pool.

**Comment by cdarken** [comment] 2018-04-20 12:44
It would be nice to have an alternate pool option, for cases like this.

**Comment by cdarken** [comment] 2018-04-23 11:57
I noticed a new issue with the latest version, also on f2pool. The miner keeps receiving jobs, but even at a very low diff like 0.2 it doesn't submit any shares. The previous version works.

**Comment by todxx** [comment] 2018-04-25 07:55
Thanks for this bug report, and my apologies for not responding sooner.  I believe I've identified the problem and will be posting a new version soon that should fix this.

**Comment by todxx** [comment] 2018-04-25 10:32
New version posted.  Please let me know if you see the problems again.  Hopefully that took care of them :)

**Comment by cdarken** [comment] 2018-04-25 10:34
Thanks. I will test and keep you posted.

**Comment by cdarken** [comment] 2018-04-25 13:33
I caught this:
```
[2018-03-25 16:29:57] Pool xzc.f2pool.com has stopped responding (64 rpcs outstanding).  Reconnecting.                                                                                        
[2018-03-25 16:29:58] Pool xzc.f2pool.com successfully subscribed.                             
[2018-03-25 16:29:58] Pool xzc.f2pool.com set difficulty to 0.249996                           
[2018-03-25 16:29:58] Pool xzc.f2pool.com received new job. (job_id: SdySIzyagQ)               
[2018-03-25 16:29:58] Pool xzc.f2pool.com authorization succeeded.                             
```
I guess it's the fix in the last version, correct? If yes, it seems to work fine.

**Comment by cdarken** [comment] 2018-04-25 20:24
It's just regular output, it receives jobs but can't seem to find any shares.

**Comment by todxx** [comment] 2018-04-25 20:51
Right, but having the exact order of events helps me debug what might be happening.  For example, do you see your GPU stats going to zero?  This might indicate that the GPUs have crashed, which is a problem that a few other people have reported, and is usually due to unstable overclocks/undervolts.

**Comment by cdarken** [comment] 2018-04-25 21:11
No, they're not going to zero, and the clocks are full throttle. There's not an issue of GPU crashing, I'm able to identify that. I will see if I catch that again. But for now these are the details that I remember:
- after the connection fails, it reconnects, it receives the low diff job, it submits shares
- after the server rises the diff to the next step, it submits at most 2 or 3 shares
- on the next diff (which is around 3 or 4 at most) it stops sending shares, like it doesn't find any

**Comment by cdarken** [comment] 2018-04-26 11:50
Ok, I caught some output. This is how it looks like:
```
[2018-03-26 14:28:21] Pool xzc.f2pool.com has stopped responding (64 rpcs outstanding). Reconnecting.              
[2018-03-26 14:28:22] Pool xzc.f2pool.com successfully subscribed.                                                  
[2018-03-26 14:28:23] Pool xzc.f2pool.com set difficulty to 0.249996                                                
[2018-03-26 14:28:23] Pool xzc.f2pool.com received new job. (job_id: TCZHtUNs7K)                                    
[2018-03-26 14:28:23] Pool xzc.f2pool.com authorization succeeded.                                                  
[2018-03-26 14:28:23] Pool xzc.f2pool.com share accepted.                                                           
[2018-03-26 14:28:24] Pool xzc.f2pool.com share accepted.                                                           
[2018-03-26 14:28:24] Pool xzc.f2pool.com share accepted.                                                           
[2018-03-26 14:28:24] Pool xzc.f2pool.com share accepted.                                                           
[2018-03-26 14:28:25] Pool xzc.f2pool.com share accepted.                                                           
[2018-03-26 14:28:25] Pool xzc.f2pool.com share accepted.                                                           
[2018-03-26 14:28:43] Pool xzc.f2pool.com received new job. (job_id: TCZHtLKqko)                                    
[2018-03-26 14:28:43] Pool xzc.f2pool.com share accepted.                                                           
[2018-03-26 14:28:43] Pool xzc.f2pool.com share accepted.                                                           
[2018-03-26 14:28:43] Pool xzc.f2pool.com share accepted.                                                           
[2018-03-26 14:28:43] Pool xzc.f2pool.com share accepted.                                                           
[2018-03-26 14:28:43] Pool xzc.f2pool.com share accepted.                                                           
[2018-03-26 14:28:43] Pool xzc.f2pool.com set difficulty to 0.999985                                                
[2018-03-26 14:28:43] Pool xzc.f2pool.com received new job. (job_id: Vra34FAhLL)                                    
[2018-03-26 14:28:43] Pool xzc.f2pool.com share accepted.                                                           
[2018-03-26 14:28:49] Stats GPU 0 - lyra2z: 3.413Mh/s (3.481Mh/s)                                                   
[2018-03-26 14:28:49] Stats GPU 1 - lyra2z: 3.080Mh/s (3.141Mh/s)                                                   
[2018-03-26 14:28:49] Stats Total - lyra2z: 6.493Mh/s (6.621Mh/s)                                                   
[2018-03-26 14:28:50] Pool xzc.f2pool.com share accepted.                                                           
[2018-03-26 14:29:20] Pool xzc.f2pool.com set difficulty to 1.999969                                                
[2018-03-26 14:29:20] Pool xzc.f2pool.com received new job. (job_id: XC5Qeh5cdc)                                    
[2018-03-26 14:29:49] Stats GPU 0 - lyra2z: 3.484Mh/s (3.481Mh/s)                                                   
[2018-03-26 14:29:49] Stats GPU 1 - lyra2z: 3.144Mh/s (3.141Mh/s)                                                   
[2018-03-26 14:29:49] Stats Total - lyra2z: 6.628Mh/s (6.621Mh/s)                                                   
[2018-03-26 14:29:49] Pool xzc.f2pool.com received new job. (job_id: XC5Qeh7l2M)                                    
[2018-03-26 14:29:51] Pool xzc.f2pool.com set difficulty to 7.999878                                                
[2018-03-26 14:29:51] Pool xzc.f2pool.com received new job. (job_id: Zr6Bpaxbct)                                    
[2018-03-26 14:29:55] Pool xzc.f2pool.com share accepted.                                                           
[2018-03-26 14:30:28] Pool xzc.f2pool.com received new job. (job_id: Zr6BpazZlm)                                    
[2018-03-26 14:30:35] Pool xzc.f2pool.com share accepted.                                                           
[2018-03-26 14:30:49] Stats GPU 0 - lyra2z: 3.479Mh/s (3.481Mh/s)                                                   
[2018-03-26 14:30:49] Stats GPU 1 - lyra2z: 3.139Mh/s (3.141Mh/s)                                                   
[2018-03-26 14:30:49] Stats Total - lyra2z: 6.619Mh/s (6.621Mh/s)                                                   
[2018-03-26 14:31:33] Pool xzc.f2pool.com received new job. (job_id: Zr6Bpb27La)                                    
[2018-03-26 14:31:49] Stats GPU 0 - lyra2z: 3.484Mh/s (3.481Mh/s)                                                   
[2018-03-26 14:31:49] Stats GPU 1 - lyra2z: 3.144Mh/s (3.141Mh/s)                                                   
[2018-03-26 14:31:49] Stats Total - lyra2z: 6.628Mh/s (6.621Mh/s)                                                   
[2018-03-26 14:32:49] Stats GPU 0 - lyra2z: 3.479Mh/s (3.481Mh/s)                                                   
[2018-03-26 14:32:49] Stats GPU 1 - lyra2z: 3.144Mh/s (3.141Mh/s)                                                   
[2018-03-26 14:32:49] Stats Total - lyra2z: 6.623Mh/s (6.621Mh/s)                                                   
[2018-03-26 14:32:53] Pool xzc.f2pool.com received new job. (job_id: Zr6Bpb4EoY)                                    
[2018-03-26 14:33:25] Pool xzc.f2pool.com received new job. (job_id: Zr6Bpb6P0o)                                    
[2018-03-26 14:33:49] Stats GPU 0 - lyra2z: 3.484Mh/s (3.481Mh/s)                                                   
[2018-03-26 14:33:49] Stats GPU 1 - lyra2z: 3.139Mh/s (3.141Mh/s)                                                   
[2018-03-26 14:33:49] Stats Total - lyra2z: 6.624Mh/s (6.621Mh/s)                                                   
[2018-03-26 14:34:17] Pool xzc.f2pool.com set difficulty to 15.999756                                               
[2018-03-26 14:34:17] Pool xzc.f2pool.com received new job. (job_id: bBbZQ31KJ5)                                    
[2018-03-26 14:34:23] Pool xzc.f2pool.com received new job. (job_id: bBbZQ33UyE)                                    
[2018-03-26 14:34:49] Stats GPU 0 - lyra2z: 3.479Mh/s (3.481Mh/s)                                                   
[2018-03-26 14:34:49] Stats GPU 1 - lyra2z: 3.144Mh/s (3.141Mh/s)                                                   
[2018-03-26 14:34:49] Stats Total - lyra2z: 6.623Mh/s (6.621Mh/s)                                                   
[2018-03-26 14:35:18] Pool xzc.f2pool.com set difficulty to 7.999878                                                
[2018-03-26 14:35:18] Pool xzc.f2pool.com received new job. (job_id: Zr6BpbAhXi)                                    
[2018-03-26 14:35:32] Pool xzc.f2pool.com share accepted.                                                           
[2018-03-26 14:35:48] Pool xzc.f2pool.com share accepted.                                                           
[2018-03-26 14:35:49] Stats GPU 0 - lyra2z: 3.484Mh/s (3.481Mh/s)                                                   
[2018-03-26 14:35:49] Stats GPU 1 - lyra2z: 3.139Mh/s (3.141Mh/s)                                                   
[2018-03-26 14:35:49] Stats Total - lyra2z: 6.624Mh/s (6.621Mh/s)                                                   
[2018-03-26 14:36:21] Pool xzc.f2pool.com received new job. (job_id: Zr6BpbCf9a)                                    
[2018-03-26 14:36:49] Stats GPU 0 - lyra2z: 3.479Mh/s (3.481Mh/s)                                                   
[2018-03-26 14:36:49] Stats GPU 1 - lyra2z: 3.144Mh/s (3.141Mh/s)                                                   
[2018-03-26 14:36:49] Stats Total - lyra2z: 6.623Mh/s (6.621Mh/s)                                                   
[2018-03-26 14:37:04] Pool xzc.f2pool.com set difficulty to 3.999939                                                
[2018-03-26 14:37:04] Pool xzc.f2pool.com received new job. (job_id: YWaoF9Jvr4)                                    
```

Compared to a restart:
```
[2018-03-26 14:38:34] Successfully initialized GPU 0: (null) with 36 CU           
[2018-03-26 14:38:34] Successfully initialized GPU 1: (null) with 32 CU           
[2018-03-26 14:38:34] Dev pool connected and ready.                               
[2018-03-26 14:38:35] Pool xzc.f2pool.com successfully subscribed.                
[2018-03-26 14:38:35] Pool xzc.f2pool.com set difficulty to 0.249996              
[2018-03-26 14:38:35] Pool xzc.f2pool.com received new job. (job_id: TC2uFle2sw)  
[2018-03-26 14:38:35] Pool xzc.f2pool.com authorization succeeded.                
[2018-03-26 14:38:35] Pool xzc.f2pool.com share accepted.                         
[2018-03-26 14:38:40] Pool xzc.f2pool.com share accepted.                         
[2018-03-26 14:38:40] Pool xzc.f2pool.com share accepted.                         
[2018-03-26 14:38:56] Pool xzc.f2pool.com received new job. (job_id: TC2uFlgE58)  
[2018-03-26 14:38:56] Pool xzc.f2pool.com share accepted.                         
[2018-03-26 14:38:56] Pool xzc.f2pool.com share accepted.                         
[2018-03-26 14:38:56] Pool xzc.f2pool.com share accepted.                         
[2018-03-26 14:38:56] Pool xzc.f2pool.com share accepted.                         
[2018-03-26 14:38:56] Pool xzc.f2pool.com set difficulty to 0.999985              
[2018-03-26 14:38:56] Pool xzc.f2pool.com received new job. (job_id: Vr3fQfW4ff)  
[2018-03-26 14:39:20] Pool xzc.f2pool.com share accepted.                         
[2018-03-26 14:39:20] Pool xzc.f2pool.com received new job. (job_id: Vr3fQocUMA)  
[2018-03-26 14:39:27] Pool xzc.f2pool.com set difficulty to 1.999969              
[2018-03-26 14:39:27] Pool xzc.f2pool.com received new job. (job_id: XBZ31GXPeR)  
[2018-03-26 14:39:34] Stats GPU 0 - lyra2z: 3.413Mh/s (3.407Mh/s)                 
[2018-03-26 14:39:34] Stats GPU 1 - lyra2z: 3.080Mh/s (3.080Mh/s)                 
[2018-03-26 14:39:34] Stats Total - lyra2z: 6.493Mh/s (6.487Mh/s)                 
[2018-03-26 14:40:01] Pool xzc.f2pool.com set difficulty to 3.999939              
[2018-03-26 14:40:01] Pool xzc.f2pool.com received new job. (job_id: YW4QbiSKwi)  
[2018-03-26 14:40:04] Pool xzc.f2pool.com share accepted.                         
[2018-03-26 14:40:04] Pool xzc.f2pool.com share accepted.                         
[2018-03-26 14:40:04] Pool xzc.f2pool.com share accepted.                         
[2018-03-26 14:40:04] Pool xzc.f2pool.com share accepted.                         
[2018-03-26 14:40:31] Pool xzc.f2pool.com set difficulty to 7.999878              
[2018-03-26 14:40:31] Pool xzc.f2pool.com received new job. (job_id: ZqZoCANGEz)  
[2018-03-26 14:40:34] Stats GPU 0 - lyra2z: 3.484Mh/s (3.446Mh/s)                 
[2018-03-26 14:40:34] Stats GPU 1 - lyra2z: 3.144Mh/s (3.112Mh/s)                 
[2018-03-26 14:40:34] Stats Total - lyra2z: 6.628Mh/s (6.558Mh/s)                 
[2018-03-26 14:41:03] Pool xzc.f2pool.com received new job. (job_id: ZqZoCAQcZ4)  
[2018-03-26 14:41:13] Pool xzc.f2pool.com share accepted.                         
[2018-03-26 14:41:34] Stats GPU 0 - lyra2z: 3.479Mh/s (3.457Mh/s)                 
[2018-03-26 14:41:34] Stats GPU 1 - lyra2z: 3.144Mh/s (3.123Mh/s)                 
[2018-03-26 14:41:34] Stats Total - lyra2z: 6.623Mh/s (6.579Mh/s)                 
[2018-03-26 14:41:35] Pool xzc.f2pool.com received new job. (job_id: ZqZoC1NPsc)  
[2018-03-26 14:41:50] Pool xzc.f2pool.com share accepted.                         
[2018-03-26 14:42:08] Pool xzc.f2pool.com share accepted.                         
[2018-03-26 14:42:14] Pool xzc.f2pool.com received new job. (job_id: ZqZoC1OszO)  
[2018-03-26 14:42:25] Pool xzc.f2pool.com share accepted.                         
[2018-03-26 14:42:34] Stats GPU 0 - lyra2z: 3.484Mh/s (3.464Mh/s)                 
[2018-03-26 14:42:34] Stats GPU 1 - lyra2z: 3.139Mh/s (3.127Mh/s)                 
[2018-03-26 14:42:34] Stats Total - lyra2z: 6.624Mh/s (6.590Mh/s)                 
[2018-03-26 14:42:39] Pool xzc.f2pool.com received new job. (job_id: ZqZoC1PsGM)  
[2018-03-26 14:42:46] Pool xzc.f2pool.com received new job. (job_id: ZqZoC1Q9aA)  
[2018-03-26 14:42:51] Pool xzc.f2pool.com received new job. (job_id: ZqZoC1QMuE)  
[2018-03-26 14:42:56] Pool xzc.f2pool.com received new job. (job_id: ZqZoC1QYMg)  
[2018-03-26 14:42:59] Pool xzc.f2pool.com received new job. (job_id: ZqZoC1Qed4)  
[2018-03-26 14:43:06] Pool xzc.f2pool.com received new job. (job_id: ZqZoC1Qvoc)  
[2018-03-26 14:43:09] Pool xzc.f2pool.com share accepted.                         
[2018-03-26 14:43:18] Pool xzc.f2pool.com share accepted.                         
[2018-03-26 14:43:19] Pool xzc.f2pool.com share accepted.                         
[2018-03-26 14:43:34] Stats GPU 0 - lyra2z: 3.479Mh/s (3.467Mh/s)                 
[2018-03-26 14:43:34] Stats GPU 1 - lyra2z: 3.144Mh/s (3.130Mh/s)                 
[2018-03-26 14:43:34] Stats Total - lyra2z: 6.623Mh/s (6.597Mh/s)                 
[2018-03-26 14:43:38] Pool xzc.f2pool.com share accepted.                         
[2018-03-26 14:43:56] Pool xzc.f2pool.com received new job. (job_id: ZqZoC1SuMI)  
[2018-03-26 14:43:59] Pool xzc.f2pool.com share accepted.                         
[2018-03-26 14:44:34] Stats GPU 0 - lyra2z: 3.484Mh/s (3.470Mh/s)                 
[2018-03-26 14:44:34] Stats GPU 1 - lyra2z: 3.144Mh/s (3.132Mh/s)                 
[2018-03-26 14:44:34] Stats Total - lyra2z: 6.628Mh/s (6.602Mh/s)                 
[2018-03-26 14:44:41] Pool xzc.f2pool.com received new job. (job_id: ZqZoCAZkPu)  
[2018-03-26 14:45:30] Pool xzc.f2pool.com set difficulty to 1.999969              
[2018-03-26 14:45:30] Pool xzc.f2pool.com received new job. (job_id: XBZ317gjTS)  
[2018-03-26 14:45:33] Pool xzc.f2pool.com share accepted.                         
[2018-03-26 14:45:34] Stats GPU 0 - lyra2z: 3.479Mh/s (3.471Mh/s)                 
[2018-03-26 14:45:34] Stats GPU 1 - lyra2z: 3.139Mh/s (3.133Mh/s)                 
[2018-03-26 14:45:34] Stats Total - lyra2z: 6.619Mh/s (6.605Mh/s)                 
[2018-03-26 14:45:37] Pool xzc.f2pool.com share accepted.                         
[2018-03-26 14:45:37] Pool xzc.f2pool.com share accepted.                         
[2018-03-26 14:45:37] Pool xzc.f2pool.com share accepted.                         
[2018-03-26 14:45:48] Pool xzc.f2pool.com share accepted.                         
[2018-03-26 14:45:50] Pool xzc.f2pool.com share accepted.                         
[2018-03-26 14:45:53] Pool xzc.f2pool.com share accepted.                         
[2018-03-26 14:45:57] Pool xzc.f2pool.com share accepted.                         
[2018-03-26 14:45:58] Pool xzc.f2pool.com share accepted.                         
```
I might imagine things, but it looks like there are way less shares after automatic reconnect.

**Comment by todxx** [comment] 2018-04-26 18:00
It appears that the pool over-reacts in terms of setting difficulty. You can see it in these lines:
`[2018-03-26 14:29:51] Pool xzc.f2pool.com set difficulty to 7.999878`
`[2018-03-26 14:34:17] Pool xzc.f2pool.com set difficulty to 15.999756`
`[2018-03-26 14:35:18] Pool xzc.f2pool.com set difficulty to 7.999878`
Which makes it very unlikely for you to find a share while the difficulty is set that high.

If you just leave the miner running, eventually the pool will lower it's difficulty to a more reasonable level.  I cannot see anything that the miner is doing incorrectly here.  Any other miner would end up doing the same thing as this scenario is caused by the difficulty the pool sends.  If your pool has a different stratum with an initial difficulty a bit higher than 0.25, say around 2-3, that will make the var-diff bounce not be so drastic on connect/reconnect.

**Comment by pcollinsca47** [comment] 2018-04-27 14:14
2.2.1 has trouble at times similar to 2.2.0 with going to 0 hash forever. 
This is with f2pool and stock clocks - all cards are at factory settings, never been overclocked.
I've included a full listing of outputs as well as a shorter one just showing the end state.





[log.2.2.1_2_short.txt](https://github.com/todxx/tdxminer/files/1955424/log.2.2.1_2_short.txt)
[log.2.2.1_2_long.txt](https://github.com/todxx/tdxminer/files/1955427/log.2.2.1_2_long.txt)

**Comment by pcollinsca47** [comment] 2018-04-27 14:24
btw a 4 card (rx 480) rig gives about 14mh/s and has no trouble finding shares with difficulty set to
15:

[2018-03-27 09:21:30] Pool xzc.f2pool.com share accepted.
[2018-03-27 09:21:30] Pool xzc.f2pool.com share accepted.
[2018-03-27 09:21:34] Pool xzc.f2pool.com set difficulty to 15.999756
[2018-03-27 09:21:34] Pool xzc.f2pool.com received new job. (job_id: acyyJpK983)
[2018-03-27 09:21:35] Pool xzc.f2pool.com share accepted.
[2018-03-27 09:21:35] Pool xzc.f2pool.com share accepted.

**Comment by pcollinsca47** [comment] 2018-04-27 14:46
Yes, f2pool connections get confused. It can be ok for hours and then get into a bad state in several ways. Sometimes error messages forever, sometimes failing to submit shares and having the card hash rates drift to 0.  For comparison I'm running several nvida cards against f2pool using ccminer on xzc without problems during the same times. 2.2.0 seems a bit better than 2.2.1 but both have similar problems with f2pool. Restarting eventually makes 2.2.0 better for a while, but 2.2.1 often quickly goes back into a bad state after restarting. Really hurts the effective hash rate over time. When the miner runs cleanly for hours it's a very good miner for amd cards. My best stretch of clean mining with tdx the last 3 days is about 13 hours with 2.2.0

**Comment by todxx** [comment] 2018-05-02 07:32
I've identified one deadlock case that can be hit when the pool connection is dropped, and it has been fixed in the release I just posted (v0.2.2.2).  I believe that it is causing the problem you are seeing, but I am not entirely sure.  Please try out the new version and let me know if the problem persists.

**Comment by cdarken** [comment] 2018-05-04 19:50
The issue seems to be fixed now. If @pcollinsca47 will confirm, the issue can be closed.

**Comment by todxx** [comment] 2018-05-13 07:56
It seems that this issue has been resolved, closing.

**Closed by todxx** 2018-05-13 07:56 UTC
